#! /bin/bash

About=$( echo "   Lexicon:	 An Instant Dictionary

   Version:	 2.0

   Developer:	 Sumit Dhingra

   E-mail:	 	LinuxSDA@gmail.com

 	 )

yad --title="Lexicon" --center --width=600 --no-buttons --text="$About"
