#! /bin/bash

meaning()
{
	Meaning="$( ( sqlite3 "$path2/data.db" "SELECT definition FROM entries WHERE word LIKE '$word' COLLATE NOCASE;" ) \
                                | tr "\n" "~" |rev|cut -c 2- |rev )"

        echo $Meaning > $path1/dump/word.html

        sed -i 's/\.~/\.\n\n➤ /g' $path1/dump/word.html

        sed -i 's/~ / /g' $path1/dump/word.html

        sed -i 's/~/\.\n\n➤ /g' $path1/dump/word.html

        sed -i 's/;.*/./g' $path1/dump/word.html

	Meaning=$( cat $path1/dump/word.html| head -5)


	Check=$(echo $Meaning|cut -c 1-5|tr " " ".")

        if [ -z $Check ]
          then

                notify-send -t 900 "Stealing Definations..."
		
                word=$(echo $word |tr '[:upper:]' '[:lower:]')

                curl -L -s https://en.m.wiktionary.org/wiki/"$word"> $path1/dump/word.html


		phonetic=$(grep -i "phonetic" $path1/dump/word.html|sed 's/>:/\n/g'|grep '^ '\
					| tr '>' '\n' | grep '^/' | cut -d '<' -f 1 | head -1)


                sed -i 's/<ol>/`/g' $path1/dump/word.html

                sed -i 's/<\/ol>/`/g' $path1/dump/word.html

                Meaning="$(tr "\n" "^" < $path1/dump/word.html | cut -d "\`" -f 2 | tr "^" "\n" | grep "^<li>" \
                                      | tr ">" "\n" | cut -d "<" -f 1  | tr "\n" " " \
                                      | tr -s " " | tr "\`" "\n" | cut -d "." -f 1)"

                Check=$(echo $Meaning | cut -c 1-5|tr " " ".")

                        if [ -z $Check ]
                         then
                                Meaning=" Not conneted/Not found "
                        fi


  		echo $Meaning > $path1/dump/word.html
       		
		sed -i 's/;/\n➤ /g' $path1/dump/word.html
        	
		Meaning=$(cat $path1/dump/word.html)

        fi

}



synonym()
{

       Synonym="$(sqlite3 "$path2/synonym.db" "SELECT synonym FROM SynonymData WHERE entries LIKE '$word' COLLATE NOCASE;")"

	Synonym="$(echo $Synonym|sed 's/#/, /g'|cut -c 2- |sed 's/`/\n/g'|head -n -1| head -2 |\
									cut -d "," -f 2,3|tr '\n' '.')"

	Check="$(echo $Synonym | cut -c 1-5|tr " " ".")"


    if [ -z $Check ]

      then
		notify-send -t 900 "Stealing Synonyms..."

		curl -L -s http://www.synonym.com/synonyms/"$word" > $path1/dump/Synonym.html


                sed -i 's/<div .*>/ /g'          $path1/dump/Synonym.html
                sed -i 's/<\/div>/ /g'           $path1/dump/Synonym.html
                sed -i 's/<h3 class="term">/~/g' $path1/dump/Synonym.html


                tr "\n" "\`" < $path1/dump/Synonym.html | cut -d "~" -f 2-3 |\
                tr "\`>~" "\n" | tr -s " "|grep "^.[A-Za-z0-9.]"|\
                sed 's/<.*/ /g'> $path1/dump/Synonym.txt


                tr "\n" "~" <$path1/dump/Synonym.txt|sed 's/height="0".*/Not Found/g'|tr "~" "\n" > $path1/dump/Synonym.html
                                                     

                sed -i "s/&#39;/'/g" $path1/dump/Synonym.html         #for apostrophe' bug


        Synonym="$(tr "\n" ","<$path1/dump/Synonym.html|sed 's/Synonym.com.*/ /g'|sed 's/, ,/~/g'|sed 's/ , /\n\n/g'|\
                   sed 's/ ,/\n/g'|sed 's/,/ /g'|sed 's/ ~/, /g'|sed 's/[02-9]./\n➤/g'|\
                   sed 's/[1]./➤/g'|cut -d "," -f 1-2|egrep "(➤|Synonyms)" )"                                                 #Formatting

        fi

}


translate()
{

	case "$check2" in
	Arabic)		t=ar;;
	Chinese)	t=zh-CN;;
	French)		t=fr;;
	German)		t=de;;
	Hebrew)		t=iw;;
	Hindi)		t=hi;;
	Italian)	t=it;;
	Japanese)	t=ja;;
	Latin)		t=la;;
	Portuguese)	t=pt;;
	Russian)	t=ru;;
	Spanish)  	t=es;;
	*) 		t=en;;

	esac

#	notify-send -t 900 "Fetching Translation..."

curl -L -s -i -A "" -d "sl=en" -d "tl=$t" --data-urlencode "text=$word" -d "submit=Translate"\
						https://translate.google.com/> $path1/dump/Translate.txt

Translation="$(html2text -utf8 $path1/dump/Translate.txt|tail -12|head -5|tr "\n" "~"|sed 's/.*\[File]/ /g'|cut -d "~" -f 2)"

}


#.........................................................................................................................#
#.........................................................................................................................#
#.........................................................................................................................#

path1="$HOME/.lexicon"
path2="/usr/share/lexicon"
word=$(xsel -o)

safe=$word

if [ "$word" ]
 
  then
	 check1=$(cat $path1/dump/Auto)					# Checks if autocorrect is 'Yes'
	 check2=$(cat $path1/dump/Lang)					# Checks Translation language.

	       if [ "$check1" = "Yes" ]
	         then
	              word="$(/usr/lib/lexicon/AutoCorrect "$word")"	# Empty string if word not found.

	            if [ -z $word ]
		     then
			word=$safe					# Put original word back in, if word is empty.
		     fi
		fi


	meaning	

	synonym 


notify-send -t 6000 "$word	$phonetic" "➤ $Meaning\n--------------------------Synonyms---------------------------\n$Synonym"

 Translation="None"	

	if [ "$check2" != "None"  ]
	  then
		translate
		notify-send -t 3000 "$check2 Translation: $Translation"
	  fi

  fi
